language: cpp
sudo: required

matrix:
    include:
        - dist: xenial
          compiler: gcc
        - dist: trusty
          compiler: gcc

branches:
    only:
        - master

before_install: 
  - cd travis-ci
  - chmod -x before_install.sh
  - chmod -x build.sh
  - cd ..
  - bash ./travis-ci/before_install.sh

script: bash ./travis-ci/build.sh

