language: cpp
sudo: required

matrix:
    include:
        - dist: precise
          compiler: gcc
        - dist: trusty
          compiler: gcc

branches:
    only:
        - master

before_install: 
  - chmod +x /travis-ci/before_install.sh
  - chmod +x /travis-ci/build.sh
  - bash ./travis-ci/before_install.sh

script: bash ./travis-ci/build.sh

